ADCGroup_Booking/ADCGroup_WebUI/Controllers/BuildingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ADCGroup_WebUI.Controllers
{
    public class BuildingController : BaseController
    {
        // GET: Building
        public ActionResult Index(string _username)
        {
            ViewBag.Name = _username;
            return View();
        }
    }
}

ADCGroup_Booking/ADCGroup_WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ADCGroup_Booking/ADCGroup_WebUI/Views/Shared/_Layout_FullWidth.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ADC Booking</title>
    <link rel="icon" type="image/png" href="~/Asset/images/Logo2.png" />
    <link href="~/Asset/css/styleBasicLayout.css" rel="stylesheet" />
    <link href="~/Asset/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Asset/css/styleNpLayout.css" rel="stylesheet" />
    <link href="~/Asset/css/stypeNp-HomeBooking.css" rel="stylesheet" />
</head>
<body>
    <section class="c-menu-slider">
        <input type="checkbox" name="c-menu-btn" id="c-menu-btn">
        <label for="c-menu-btn" class="c-menu-btn">
            <div class="c-menu-btn__indicator">
                <div class="c-menu-btn__indicator--1"></div>
                <div class="c-menu-btn__indicator--2"></div>
                <div class="c-menu-btn__indicator--3"></div>
            </div>
        </label>
        <label for="c-menu-btn" class="c-menu-btn--is-active"></label>
        <div class="c-menu-slider__content">
            <ul class="c-menu-items">
                <li class='item-1'>@Html.ActionLink("Trang Chủ", "Index", "Home")</li>
                <li class='item-2'>@Html.ActionLink("Phòng Họp", "HomeBooking", "Home")</li>
                <li class='item-3'>@Html.ActionLink("Building...", "Index", "Building")</li>
                <li class='item-4'>@Html.ActionLink("Building...", "Index", "Building")</li>
                <li class='item-5'>@Html.ActionLink("Building...", "Index", "Building")</li>
            </ul>
            <a href="/Login/Home" class="c-menu-btn-bottom">
                Đăng Xuất
                <hr class="c-menu-btn-bottom-underline">
            </a>
        </div>
    </section>
    <!--===== END OF RIGHT SLIDER MENU =====-->
    <section class="main">
        @RenderBody()
    </section>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>